config/routes.rb
Rails.application.routes.draw do

  root "static#home"
  get "about", to: "static#about"

  # get 'login', to: "sessions#new"
  post 'login', to: "sessions#create"
  delete  'logout', to: "sessions#destroy"
  
  resources :archers, only: [:show, :new, :create, :edit, :update]
  resources :score_sessions
  
  get '/score_sessions/:id/score', to: 'score_sessions#score', as: 'score'
  patch '/score_sessions/:id/score', to: 'score_sessions#update_score', as: "update_score"
  patch '/score_sessions/:id/score/rset', to: 'score_sessions#update_score_rset', as: "update_score_rset"
  patch '/score_sessions/:id/score/round', to: 'score_sessions#update_score_round', as: "update_score_round"

  resources :rounds, only: [:edit, :update]
  # resources :shots, only: [:edit, :update]
  
  
  
end

app/models/rset.rb
class Rset < ApplicationRecord
    has_many :ends, dependent: :destroy
    has_many :shots, dependent: :destroy
    belongs_to :archer
    belongs_to :score_session
    belongs_to :round
    belongs_to :set_end_format, class_name: "Format::SetEndFormat"
    belongs_to :distance_target_category, class_name: "Organization::DistanceTargetCategory"
    has_one :target, through: :distance_target_category
    has_one :alt_target, through: :distance_target_category

    # assoc attrs - :archer_id, :score_session_id, :round_id, :set_end_format_id
    # data attrs - :name, :date, :rank
    # user attrs - :date, :rank
    # DEPENDENCIES: 
        # Primary: ScoreSession (for date validation), Round, SetEndFormat (auto-assign name) - need one SetEndFormat per Rset in same Round, DistanceTargetCategory (for auto_assign)
        # Secondary: Archer (for Round), RoundFormat (for SetEndFormat)
        # Tertiary: Division, AgeClass, Gender (for Archer - non-assoc)

    validates :name, 
        presence: true, 
        uniqueness: { case_sensitive: false, scope: :round }
    # validates :rank, 
    #     presence: { message: "You must enter a rank if Set/Distance complete." }, 
    #     if: :complete?
    validate :check_associations, :check_date, :check_and_assign_rank
    before_validation :assign_name, :assign_dist_targ_cat
    

    # ##### helpers (callbacks & validations)
    def assign_name
        if self.round && self.set_end_format
            self.name = create_name
        end
    end

    def create_name
        "#{self.round.name} - #{self.set_end_format.name}"
    end

    def check_date
        if self.score_session.single_day?
            self.date = self.score_session.start_date
        elsif date_required?
            errors.add(:date, "Date must be between #{self.score_session.start_date} and #{self.score_session.end_date}.") if invalid_date?
        elsif self.date
            errors.add(:date, "Date must be between #{self.score_session.start_date} and #{self.score_session.end_date} or leave blnak.") if invalid_date?
        end
    end

    def date_required?
        self.id && (self.scoring_started? || self.active?)
    end

    def date_out_of_range?
        self.date < self.score_session.start_date || self.date > self.score_session.end_date
    end

    def invalid_date?
        if date_required?
            self.date.blank? || date_out_of_range?
        else
            date_out_of_range?
        end
    end

    def archer_category
        self.round.archer_category if self.round
    end

    def assign_dist_targ_cat
        if self.set_end_format && self.archer_category
            self.distance_target_category = find_dist_targ_cat
        end
    end

    def find_dist_targ_cat
        Organization::DistanceTargetCategory.find_dtc_by_set_cat(set_end_format: self.set_end_format, archer_category: self.archer_category)
    end
    

    # ##### helpers (data control)
    def distance
        self.distance_target_category.distance
    end

    # not sure if I need this - test in spec file, also commented out
    # def round_format
    #     self.round.round_format
    # end

    def num_ends
        self.set_end_format.num_ends
    end

    def shots_per_end
        self.set_end_format.shots_per_end
    end

    def num_ends
        self.set_end_format.num_ends
    end

    def shots_per_rset
        self.shots_per_end*self.num_ends
    end

    def set_num
        self.name.last.to_i
    end

    def previous_rset
        self.round.rsets.find_by(name: "#{self.round.name} - Set/Distance#{set_num-1}")
    end

    def previous_rset_active?
        self.previous_rset ? self.previous_rset.active : false
    end

    # def active?
    #     if set_num == 1 
    #         self.incomplete?
    #     else
    #         # previous = Rset.find_by(name: "#{self.round.name} - Set/Distance#{set_num-1}")
    #         previous = self.round.rsets.find_by(name: "#{self.round.name} - Set/Distance#{set_num-1}")
    #         previous.complete? && self.incomplete?
    #     end
    # end
end

app/views/rsets/_rset.html.erb
<section id=<%= "rset-#{rset.id}" %> class="rset-section">
    <section id=<%= "rset-#{rset.id}-info" %> class="rset-info">
        <%= tag.h4 "#{rset.set_end_format.name} - #{rset.distance}", class: "short-bottom-margin" %>
        
        <% # if score_functionality? && (rset.complete? || rset.active) %>
        <% if score_functionality? && rset.active && !rset.previous_rset_active? %>
            <%= form_for rset, url: update_score_rset_path(@score_session) do |rset_f| %>
                <%= rset_f.hidden_field :id %>
                <% assign_round_or_rset_errors(rset_f.object, :rset) %>

                <%= render partial: "rsets/rset_form", locals: {rset_f: rset_f} %>
            <% end %>
        <% else %>
            <%= display_detail("Date", formatted_date(rset.date)) %>
            <%= display_detail("Rank", get_rank(rset)) %>
        <% end %>

        <%= display_detail("Rank", get_rank(rset)) if score_functionality? && rset.incomplete? %>
        <%= display_detail("Target", rset.target.name) %>
        <%= display_detail("Score", rset.score) %>
        
        <section id=<%= "rset-#{rset.id}-scores" %> class="all-scores">
            <%= render partial: "ends/scores_table", locals: {ends: rset.ends, builder_end: rset.ends.first} %>
        </section>
    </section>
</section>

app/views/rsets/_rset_form.html.erb
<%= tag.h4 "#{rset_f.object.set_end_format.name} - #{rset_f.object.distance}", class: "short-margins" unless score_functionality? %>

<section class="rset-form-fields">
    <div class="form-field-group">
        <%= build_form_input(rset_f, "date", :date, rset_f.object, nil, ("required" if rset_f.object.scoring_started?) ) %>
        <%= build_form_input(rset_f, "text", :rank, rset_f.object, "Your final place for the set/distance", nil) if (rset_f.object.complete? && rset_f.object.active) %>
        
        <% if score_functionality? %>
            <%= tag.p (rset_f.submit "Select Date to Start"), class: "display-horiz" if !rset_f.object.date %>
            <%= tag.p (rset_f.submit "Update Set/Distance"), class: "display-horiz" if (rset_f.object.date && rset_f.object.incomplete?) %>
            <%= tag.p (rset_f.submit "Enter Rank (optional) and Finish Set/Distance"), class: "display-horiz" if (rset_f.object.complete? && rset_f.object.active) %>
        <% end %>
    </div>
</section>