config/routes.rb
Rails.application.routes.draw do

  root "static#home"
  get "about", to: "static#about"

  # get 'login', to: "sessions#new"
  post 'login', to: "sessions#create"
  delete  'logout', to: "sessions#destroy"
  
  resources :archers, only: [:show, :new, :create, :edit, :update]
  resources :score_sessions
  
  get '/score_sessions/:id/score', to: 'score_sessions#score', as: 'score'
  patch '/score_sessions/:id/score', to: 'score_sessions#update_score', as: "update_score"
  patch '/score_sessions/:id/score/rset', to: 'score_sessions#update_score_rset', as: "update_score_rset"
  patch '/score_sessions/:id/score/round', to: 'score_sessions#update_score_round', as: "update_score_round"

  resources :rounds, only: [:edit, :update]
  # resources :shots, only: [:edit, :update]
  
  
  
end

app/models/round.rb
class Round < ApplicationRecord
    has_many :rsets, dependent: :destroy
    has_many :ends, dependent: :destroy
    has_many :shots, dependent: :destroy
    belongs_to :archer
    belongs_to :score_session
    belongs_to :round_format, class_name: "Format::RoundFormat"
    belongs_to :archer_category, class_name: "Organization::ArcherCategory"
    
    # assoc attrs - :archer_id, :score_session_id, :round_format_id
    # data attrs - :name, :round_type, :score_method, :rank
    # user attrs - :round_type, :score_method, :rank
    # DEPENDENCIES: 
        # Primary: ScoreSession, RoundFormat (auto-assign name)
        # Secondary: Archer (for ScoreSession)
        # Tertiary: Division, AgeClass, Gender (for Archer - non-assoc)
    
    validates :name, 
        presence: true, 
        uniqueness: { case_sensitive: false, scope: :score_session }
    validates :round_type, 
        presence: { message: "You must choose a round type." }, 
        inclusion: { in: ROUND_TYPES }
    validates :score_method, 
        presence: { message: "You must choose a score method." }, 
        inclusion: { in: SCORE_METHODS }
    # validates :rank, 
    #     presence: { message: "You must enter a rank if Set/Distance complete." }, 
    #     if: :complete?
    validate :check_associations, :check_and_assign_rank
    # validates_associated :rsets
    before_validation :assign_name


    # ##### helpers (callbacks & validations)
    # auto create name ( ScoreSession.name - RoundFormat.name )
    def assign_name
        if self.score_session && self.round_format
            self.name = create_name
        end
# binding.pry # update 3    round validation
# binding.pry # new 6       round validation
    end

    def create_name
        "#{self.score_session.name} - #{self.round_format.name}" # if self.round
    end

    # ##### helpers (data control)
    def gov_body
        self.score_session.gov_body
    end
    
    def discipline
        self.round_format.discipline
    end
    
    def division
        self.archer_category.division if archer_category
    end
    
    def age_class
        self.archer_category.age_class if archer_category
    end

    def gender
        self.archer.gender
    end
    
    def find_category_by_div_age_class(division: division, age_class: age_class)
        Organization::ArcherCategory.find_category(gov_body: self.gov_body, division: division, age_class: age_class, gender: self.gender)
    end

    def num_sets
        self.round_format.num_sets
    end

    def shots_per_round
        total_shots = 0
        self.rsets.each { |rset| total_shots += rset.shots_per_rset }
        total_shots
    end
end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController
  before_action :get_round_form_collections, only: [:edit, :update]
  # don't forget to restrict the views!!!!!

  def edit
    @round = Round.find(params[:id])
    @score_session = @round.score_session
    redirect_to score_path(@score_session) if !request.referrer
  end

  def update
    @round = Round.find(params[:id])
    @score_session = @round.score_session

    attrs = round_params
    attrs[:archer_category_id] = @round.find_category_by_div_age_class(division: attrs[:division], age_class: attrs[:age_class]).id
    attrs.delete(:division)
    attrs.delete(:age_class)
    @round.assign_attributes(attrs)

    if @round.save
      @round.rsets.each { |rset| rset.update(distance_target_category: nil) }
      redirect_to score_path(@score_session)
    else
      render :edit
    end
  end

  def round_params
    params.require(:round).permit(:round_type, :score_method, :rank, :division, :age_class)
  end
  
  def get_round_form_collections
    @round_formats = Format::RoundFormat.all
    @round_types = ROUND_TYPES
    @score_methods = SCORE_METHODS
    @divisions = Organization::Division.all
    @age_classes = current_user.eligible_age_classes # linit by ScoreSession.gov_body
  end
end

app/helpers/rounds_helper.rb
module RoundsHelper
end

app/views/rounds/_round.html.erb
<section id=<%= "round-#{round.id}" %> class="round-section">
    <% if show_action? %>    
        <section class="section-header">
            <%= tag.h3 "#{round.round_format.name} (#{round.round_type})", class: "short-bottom-margin display-horiz-hl" %>
        </section>
    <% end %>
    
    <section id=<%= "round-#{round.id}-info" %> class="round-info" >
        <%= display_detail("Round", round.round_format.name, round.round_type, "parentheses") unless show_action? %>
        <%= display_detail("Category", round.division.name, round.age_class.name) %>
        <%= display_detail("Score", round.score) %>
        <%= display_detail("Rank", get_rank(round)) %>
        <%= display_edit_link(round) if score_functionality? %>
    </section>

    <% if show_action? || score_functionality? %>
        <section id=<%= "round-#{round.id}-rsets" %> class="all-rsets">
            <%= render collection: round.rsets, partial: "rsets/rset" %>
        </section>
    <% end %>

    <% if score_functionality? && round.active && round.complete? && !round.rsets.last.active %>
        <%= form_for round, url: update_score_round_path(@score_session) do |round_f| %>
            <%= round_f.hidden_field :id %>
            <% assign_round_or_rset_errors(round_f.object, :round) %>

            <%= render partial: "rounds/round_form", locals: {round_f: round_f} %>
        <% end %>
    <% end %>
</section>

app/views/rounds/_round_form.html.erb
<%= tag.h3 round_f.object.round_format.name, class: "short-margins" if update_functionality? && !round_functionality? %>

<section class="round-form-fields">
    <% if creation_functionality? %>
        <div class="form-field-group">
            <%= build_form_collection(round_f, "models", :round_format_id, round_f.object, @round_formats, :id, (round_f.object.round_format ? round_f.object.round_format.id : nil), "required") %>
        </div>
    <% end %>

    <% if !score_functionality? %>
        <div class="form-field-group">
            <%= build_form_collection(round_f, "list_items", :round_type, round_f.object, @round_types, (round_f.object.round_type || @round_types.first), "required") %>
            <%= build_form_collection(round_f, "list_items", :score_method, round_f.object, @score_methods, (round_f.object.score_method || @score_methods.first), "required") %>
            <%= build_form_collection(round_f, "models", :division, round_f.object, @divisions, :id, (round_f.object.division ? round_f.object.division.id : @default_division.id), "required") %>
            <%= build_form_collection(round_f, "models", :age_class, round_f.object, @age_classes, :id, (round_f.object.age_class ? round_f.object.age_class.id : @default_age_class.id), "required") %>
        </div>
    <% end %>

    <% if update_functionality? || score_functionality? %>
        <div class="form-field-group">
            <%= build_form_input(round_f, "text", :rank, round_f.object, "Your final place for the round", nil) %>
        </div>
    <% end %>
</section>

<% if !score_functionality? && score_ses_f && !round_functionality? && !creation_functionality? %>
    <h3 class="short-bottom-margin">Sets/Distances In Round</h3>
    <section id="form-rset-section">
        <%= score_ses_f.fields_for :rsets do |rset_f| %>
            <% get_child_error(score_ses_f.object.rsets, rset_f.object, :date) %>
            <% get_child_error(score_ses_f.object.rsets, rset_f.object, :rank) %>
            <%= render partial: "rsets/rset_form", locals: {rset_f: rset_f} %>
        <% end %>
    </section>
<% end %>

<% if score_functionality? %>
    <%= tag.p (round_f.submit "Enter Rank (optional) and Finish Round"), class: "display-horiz" %>
<% end %>

app/views/rounds/edit.html.erb
<%= tag.h1 @round.name %>

<%= form_for(@round) do |round_f| %>
    <%= render partial: "round_form", locals: {round_f: round_f, score_ses_f: nil} %>
    
    <section id="form-submit-section" class="add-top-margin">
        <%= round_f.submit %>
        <%= display_form_cancel_link(@score_session) %>
        <%= display_required_note %>
    </section>
<% end %>