config/routes.rb
Rails.application.routes.draw do

  root "static#home"
  get "about", to: "static#about"

  # get 'login', to: "sessions#new"
  post 'login', to: "sessions#create"
  delete  'logout', to: "sessions#destroy"
  
  resources :archers, only: [:show, :new, :create, :edit, :update]
  resources :score_sessions
  
  get '/score_sessions/:id/score', to: 'score_sessions#score', as: 'score'
  patch '/score_sessions/:id/score', to: 'score_sessions#update_score', as: "update_score"
  patch '/score_sessions/:id/score/rset', to: 'score_sessions#update_score_rset', as: "update_score_rset"
  patch '/score_sessions/:id/score/round', to: 'score_sessions#update_score_round', as: "update_score_round"

  resources :rounds, only: [:edit, :update]
  # resources :shots, only: [:edit, :update]
  
  
  
end

app/models/end.rb
class End < ApplicationRecord
    has_many :shots, dependent: :destroy
    belongs_to :archer
    belongs_to :score_session
    belongs_to :round
    belongs_to :rset
        
    # assoc attrs - :archer_id, :score_session_id, :round_id, :rset_id
    # data attrs - :number, :set_score
    # user attrs - :set_score
    # DEPENDENCIES: 
        # Primary: Round (for set_score validation); Rset, SetEndFormat (auto-assign number) - need one SetEndFormat per Rset in same Round
        # Secondary: Archer, ScoreSession (for Round); RoundFormat (for Round and SetEndFormat)
        # Tertiary: Division, AgeClass, Gender (for Archer - non-assoc)

    validates :number, 
        numericality: {only_integer: true, greater_than: 0, less_than_or_equal_to: :allowable_ends_per_set }, 
        uniqueness: { scope: :rset }
    validates :set_score, 
        numericality: { 
            only_integer: true, 
            greater_than_or_equal_to: 0, 
            less_than_or_equal_to: 2, 
            allow_nil: true, 
            allow_blank: true, 
            message: "You must enter 0, 1, or 2." },
        on: :create
    validates :set_score, 
        numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 2, message: "You must enter 0, 1, or 2." },
        on: :update,
        unless: :score_method_is_points?
    validate :check_associations
    before_validation :assign_number, :clear_set_score_if_points
    before_save :score_from_shots
    

    # ##### helpers (callbacks & validations)
    def assign_number
        if self.number.blank? && self.rset
            self.number = ends_in_set.count + 1 
        end
    end

    def ends_in_set
        self.rset.ends if self.rset
    end

    def allowable_ends_per_set
        self.rset.num_ends
    end

    def score_method_is_points?
        self.round && self.round.score_method == "Points"
    end

    def clear_set_score_if_points
        self.set_score = nil if score_method_is_points?
    end

    def score_from_shots
        self.score = self.shots.collect { |shot| shot.score }.sum
    end


    # ##### helpers (associated models instantiation)
    def shots_attributes=(attributes)
        self.validate if self.id

        attributes.values.each do |attrs|
            shot = Shot.find(attrs[:id])
            shot.update(attrs)
            self.errors[:shots] << {shot.number => shot.errors.messages} if shot.errors.any?
        end
    end


    # ##### helpers (data control)
    def shots_per_end
        self.rset.shots_per_end
    end
	
    def score_method_is_set?
        self.round && self.round.score_method == "Set"
    end

    def previous_end
        self.rset.ends.find_by(number: self.number-1)
    end

    def previous_end_active?
        self.previous_end ? self.previous_end.active : false
    end

    def currently_scoring?
        self.rset.active && self.rset.date && self.active && !self.previous_end_active?
    end

    def last_end_in_rset?
        self == self.rset.ends.last
    end

    # def active?
    #     if self.rset.active?
    #         if self.number == 1 
    #             self.incomplete?
    #         else
    #             previous = self.rset.ends.find_by(number: self.number-1)
    #             previous.complete? && self.incomplete?
    #         end
    #     else
    #         false
    #     end
    # end
    
    
end

app/views/ends/_end_form.html.erb
<%= form_for endd, url: update_score_path(@score_session) do |end_f| %>
    <%= end_f.hidden_field :id %>
    <% assign_end_errors(end_f.object) %>

    <%= tag.th "End #{endd.number}" %>
    <%= end_f.fields_for :shots do |shot_f| %>
        <% get_child_error(end_f.object.shots, shot_f.object, :score_entry) %>
        <%= tag.td (shot_f.select :score_entry, options_for_select(shot_f.object.possible_scores, shot_f.object.score_entry), {prompt: ""}, class: "score-input-field"), class: "shot-score-entry" %>
    <% end %>
    <%= tag.td "", class: "spacer" %>
    <%= tag.td endd.score, class: "end-score" %>
    <%= tag.td "", class: "spacer" %>
    <%= tag.td (end_f.select :set_score, options_for_select([0, 1, 2], end_f.object.set_score), {prompt: ""}, class: "set-score-input-field"), class: "end-set-score" if endd.score_method_is_set? %>
    <%= tag.td "", class: "spacer" %>
    <%= tag.td (end_f.submit "Save Score", class: "score-submit-button"), class: "score-submit" %>

    <% if end_or_shot_errors?(endd) %>
        <tr>
            <%= tag.th %>
            <td class="spacer" colspan="6">
                <% endd.shots.each do |shot| %>
                    <%= add_error_or_note(shot, :score_entry) %>
                <% end  %>
            </td>
            <%= tag.td (add_error_or_note(end_f.object, :set_score)), {class: "spacer", colspan: "4"} if endd.score_method_is_set? %>
        </tr>
    <% end %>
<% end %>

app/views/ends/_endd.html.erb
<% if score_functionality? && endd.rset.date && endd.currently_scoring?  %>
    <tr id=<%= "end-#{endd.id}-form" %> class="end-section">
        <%= render partial: "ends/end_form", locals: {endd: endd} %>
    </tr>
<% else %>
    <tr id=<%= "end-#{endd.id}" %> class="end-section">
        <%= tag.th "End #{endd.number}" %>
        <% endd.shots.each do |shot| %>
            <%= tag.td shot.score_entry, id: "shot-#{shot.id}", class: "shot-score-entry" %>
        <% end  %>
        <%= tag.td "", class: "spacer" %>
        <%= tag.td endd.score, class: "end-score" %>
        <%= tag.td "", class: "spacer" %>
        <%= tag.td endd.set_score, class: "end-set-score" if endd.score_method_is_set? %>
    </tr>
<% end %>

app/views/ends/_scores_table.html.erb
<table>
    <thead>
        <tr>
            <%= tag.th %>
            <% builder_end.shots.each do |shot| %>
                <%= tag.th shot.number %>
            <% end %>
            <%= tag.th "", class: "spacer" %>
            <%= tag.th "Total" %>
            <%= tag.th "", class: "spacer" %>
            <%= tag.th "Set" if builder_end.score_method_is_set? %>
        </tr>
    </thead>
    <tbody>
        <%= render collection: ends, partial: "ends/endd" %>
    </tbody>
</table>