config/routes.rb
Rails.application.routes.draw do

  root "static#home"
  get "about", to: "static#about"

  # get 'login', to: "sessions#new"
  post 'login', to: "sessions#create"
  delete  'logout', to: "sessions#destroy"
  
  resources :archers, only: [:show, :new, :create, :edit, :update]
  resources :score_sessions
  
  get '/score_sessions/:id/score', to: 'score_sessions#score', as: 'score'
  patch '/score_sessions/:id/score', to: 'score_sessions#update_score', as: "update_score"
  patch '/score_sessions/:id/score/rset', to: 'score_sessions#update_score_rset', as: "update_score_rset"
  patch '/score_sessions/:id/score/round', to: 'score_sessions#update_score_round', as: "update_score_round"

  resources :rounds, only: [:edit, :update]
  # resources :shots, only: [:edit, :update]
  
  
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <title>Archery Score Tracker</title>
	  <meta name="author" content="Mark Stabler">
	  <meta name="description" content="Track all your archery scores and shots, analyze your performance."/>
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <section id="header-top">
        <h1 id="header-HL"><%= link_to "Archery Score Tracker", root_path %></h1>
        <nav id="user-nav">
          <ul>
            <li><%= link_to "About", about_path %></li>
            <% if current_user %>
              <li><%= link_to "#{current_user.first_name}'s Profile", archer_path(current_user) %></li>
              <li><%= link_to "Log Out", logout_path, method: "delete" %></li>
            <% else %>
              <li><%= link_to "Log In", root_path %></li>
              <li><%= link_to "Sign Up", new_archer_path %></li>
            <% end %>
          </ul>
        </nav>
      </section>
      <% if current_user %>
        <section id="header-bottom">
          <nav id="main-nav">
            <ul>
              <% if active_score_session? %>
                <li><%= link_to "Resume Score Session", score_path(find_active_score_session) %></li>
              <% end %>
              <li><%= link_to "Your Scores", score_sessions_path %></li>
              <li><%= link_to "Shot Analysis", "#" %></li>
              <li><%= link_to "New Score Session", new_score_session_path %></li>
              <li><%= link_to "Manage Rounds", "#" %></li>
              <li><%= link_to "Manage Targets", "#" %></li>
            </ul>
          </nav>
        </section>
      <% end %>
    </header>
    
    <main>
      <%= yield %>
    </main>

    <footer>
        <p><a href="https://www.markstabler.com" target="_blank">Created by Mark Stabler</a></p>
        <p class="display-horiz fine-print">© Stabler Writing Services, LLC</p>
        <p class="display-horiz fine-print"><a href="https://github.com/marcon29/rails-archery-score-tracker" target="_blank">MIT License & Source Code</a></p>
    </footer>
  </body>
</html>